"""
build-static.py
WordPress Static Site Builder
Fetches all pages from database (via get-all-urls.php), copies assets directly.

Usage:
    python build-static.py              # full rebuild
    python build-static.py --html-only  # re-fetch HTML only, skip asset copy (faster)

--html-only: use when WordPress settings changed but theme/plugin files did not.
             Keeps existing themes/plugins/wp-includes in deploy/, only re-fetches HTML.

Requirements:
    pip install requests
"""

import sys
import time
import shutil
import requests
import xml.etree.ElementTree as ET
from pathlib import Path
from concurrent.futures import ThreadPoolExecutor, as_completed
from urllib.parse import urlparse

# ── Configuration ──────────────────────────────────────────────
LOCAL_URL      = "http://tesstaiwan-local.local"
PROD_URL       = "https://tesstaiwan.com"
WP_ROOT        = Path(r"C:\Users\User\Local Sites\tesstaiwan-local\app\public")
OUTPUT_DIR     = Path(r"C:\Users\User\Local Sites\tesstaiwan-local\deploy")
WORKERS        = 6      # parallel page fetchers
TIMEOUT        = 90     # seconds per page
# ───────────────────────────────────────────────────────────────


def get_urls():
    """
    Get ALL public URLs from all-urls.json (generated by get-all-urls.php).
    Falls back to sitemap if the file is not found.
    """
    # --- Primary: read from disk (generated by get-all-urls.php) ---
    json_path = WP_ROOT / "wp-content" / "uploads" / "all-urls.json"
    if json_path.exists():
        import json
        data = json.loads(json_path.read_text(encoding="utf-8"))
        urls = set(u.replace(PROD_URL, LOCAL_URL) for u in data.get("urls", []))
        if urls:
            print(f"      Source: all-urls.json ({data['count']} URLs)")
            return sorted(urls)
    else:
        print(f"      all-urls.json not found, falling back to sitemap...")
        print(f"      Tip: visit http://tesstaiwan-local.local/get-all-urls.php first")

    # --- Fallback: sitemap ---
    urls = set()
    ns = "http://www.sitemaps.org/schemas/sitemap/0.9"

    def parse_sitemap(xml_text):
        try:
            root = ET.fromstring(xml_text)
            for sm in root.findall(f".//{{{ns}}}sitemap/{{{ns}}}loc"):
                sub_url = sm.text.replace(PROD_URL, LOCAL_URL)
                try:
                    r = requests.get(sub_url, timeout=TIMEOUT)
                    parse_sitemap(r.text)
                except Exception:
                    pass
            for loc in root.findall(f".//{{{ns}}}url/{{{ns}}}loc"):
                url = loc.text.replace(PROD_URL, LOCAL_URL)
                if url.startswith(LOCAL_URL):
                    urls.add(url)
        except ET.ParseError:
            pass

    for sitemap_url in [f"{LOCAL_URL}/sitemap_index.xml", f"{LOCAL_URL}/wp-sitemap.xml"]:
        try:
            r = requests.get(sitemap_url, timeout=TIMEOUT)
            if r.status_code == 200 and "<" in r.text:
                parse_sitemap(r.text)
                if urls:
                    break
        except Exception:
            continue

    urls.add(LOCAL_URL + "/")
    print(f"      Source: sitemap ({len(urls)} URLs)")
    return sorted(urls)


def url_to_filepath(url):
    """Convert a page URL to its output file path."""
    path = urlparse(url).path
    if path == "" or path == "/":
        return OUTPUT_DIR / "index.html"
    path = path.strip("/")
    # Treat paths without extension as directories with index.html
    if "." not in Path(path).name:
        return OUTPUT_DIR / path / "index.html"
    return OUTPUT_DIR / path


def fetch_page(url, session, retries=2):
    """Download one page and save it, with retries."""
    last_error = ""
    for attempt in range(retries + 1):
        try:
            r = session.get(url, timeout=TIMEOUT)
            if r.status_code != 200:
                return url, f"HTTP {r.status_code}", False

            html = r.text.replace(LOCAL_URL, PROD_URL)
            out = url_to_filepath(url)
            out.parent.mkdir(parents=True, exist_ok=True)
            out.write_text(html, encoding="utf-8", errors="replace")
            return url, "OK", True

        except requests.exceptions.Timeout:
            last_error = "timeout"
        except Exception as e:
            last_error = str(e)

    return url, last_error, False


def copy_dir(src, dst, exclude_names=None):
    """Copy a directory, optionally skipping certain subfolder names."""
    src, dst = Path(src), Path(dst)
    if not src.exists():
        return
    if dst.exists():
        shutil.rmtree(dst)

    def _ignore(dir_, files):
        return [f for f in files if f in (exclude_names or [])]

    shutil.copytree(src, dst, ignore=_ignore if exclude_names else None)


def backup_db():
    """建置前先備份 MySQL -> R2（若距上次備份 >= 30 天）"""
    import subprocess
    backup_script = Path(__file__).parent / "backup-db.py"
    if not backup_script.exists():
        return
    print("\n[0a/4] DB 備份檢查...")
    result = subprocess.run([sys.executable, str(backup_script)], cwd=str(Path(__file__).parent))
    if result.returncode != 0:
        print("  警告：DB 備份失敗，繼續 build（請手動執行 python backup-db.py）")


def sync_analytics():
    """建置前先同步 Cloudflare Analytics → wp_cocoon_accesses"""
    import subprocess
    sync_script = Path(__file__).parent / "sync-analytics.py"
    if not sync_script.exists():
        return
    print("\n[0b/4] 同步 Cloudflare Analytics...")
    result = subprocess.run([sys.executable, str(sync_script)], cwd=str(Path(__file__).parent))
    if result.returncode != 0:
        print("  警告：Analytics 同步失敗，繼續 build（人気記事排名可能非最新）")


def main():
    html_only = "--html-only" in sys.argv
    start_time = time.time()

    print("=" * 50)
    print("  WordPress Static Builder")
    if html_only:
        print("  Mode: HTML only (skipping asset copy)")
    print("=" * 50)

    # Step 0: backup DB + sync analytics
    backup_db()
    sync_analytics()

    # Step 1: collect URLs
    print("\n[1/4] Getting all URLs from WordPress database...")
    urls = get_urls()
    print(f"      Found {len(urls)} URLs")

    # Step 2: clean output
    print(f"\n[2/4] Preparing output folder...")
    if html_only:
        # Only delete HTML files, keep themes/plugins/wp-includes
        deleted = 0
        for f in OUTPUT_DIR.rglob("*.html"):
            f.unlink()
            deleted += 1
        print(f"      Cleared {deleted} HTML files (assets preserved)")
    else:
        if OUTPUT_DIR.exists():
            shutil.rmtree(OUTPUT_DIR)
        OUTPUT_DIR.mkdir(parents=True)

    # Step 3: fetch all HTML pages in parallel
    print(f"\n[3/4] Fetching {len(urls)} pages ({WORKERS} workers)...")
    ok_count = fail_count = 0
    failed_urls = []

    session = requests.Session()
    with ThreadPoolExecutor(max_workers=WORKERS) as pool:
        futures = {pool.submit(fetch_page, url, session): url for url in urls}
        for i, future in enumerate(as_completed(futures), 1):
            url, status, ok = future.result()
            short = url.replace(LOCAL_URL, "")
            if ok:
                ok_count += 1
                print(f"  [{i}/{len(urls)}] OK   {short}")
            else:
                fail_count += 1
                failed_urls.append(url)
                print(f"  [{i}/{len(urls)}] FAIL {short}  ({status})")

    print(f"\n  Pages: {ok_count} OK / {fail_count} failed")
    if failed_urls:
        Path(OUTPUT_DIR / "_failed_urls.txt").write_text("\n".join(failed_urls))
        print(f"  Failed URLs saved to deploy/_failed_urls.txt")

    if html_only:
        print("\n[4/4] Skipped (--html-only mode)")
    else:
        # Step 4: copy static assets directly from filesystem
        print("\n[4/4] Copying static assets...")

        wp_content = WP_ROOT / "wp-content"

        print("  Copying themes...")
        copy_dir(wp_content / "themes", OUTPUT_DIR / "wp-content" / "themes")

        print("  Copying plugins...")
        copy_dir(wp_content / "plugins", OUTPUT_DIR / "wp-content" / "plugins")

        print("  Copying wp-includes...")
        copy_dir(WP_ROOT / "wp-includes", OUTPUT_DIR / "wp-includes")

    # Uploads go to Cloudflare R2, NOT to Pages (would exceed 20,000 file limit)
    # Sync separately with: aws s3 sync wp-content/uploads s3://tesstaiwan-uploads ...

    # Summary
    total_files = sum(1 for _ in OUTPUT_DIR.rglob("*") if _.is_file())
    total_mb = sum(f.stat().st_size for f in OUTPUT_DIR.rglob("*") if f.is_file()) / 1_048_576

    elapsed = time.time() - start_time
    mins, secs = divmod(int(elapsed), 60)

    print("\n" + "=" * 50)
    print("  Done!")
    print(f"  Output : {OUTPUT_DIR}")
    print(f"  Files  : {total_files:,}")
    print(f"  Size   : {total_mb:,.0f} MB")
    print(f"  Time   : {mins}m {secs}s")
    print("=" * 50)
    print("\nNext: npx wrangler pages deploy deploy --project-name tesstaiwan --branch production")


if __name__ == "__main__":
    main()
